### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by NGwpower** [pololu/dual-vnh5019-motor-shield#10]
New to programing, tried running on Arduino Uno, removed it repeatedly with no access. Followed instructions and still get this message:

Arduino: 1.6.4 (Windows 7), Board: "Arduino Uno"
C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++ -c -g -Os -Wall -Wextra -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10604 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino -IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard C:\Users\RJEA26~1.STA\AppData\Local\Temp\build2119754585980147342.tmp\sketch_.cpp -o C:\Users\RJEA26~1.STA\AppData\Local\Temp\build2119754585980147342.tmp\sketch_.cpp.o  
sketch_.ino:1:36: fatal error: DualVNH5019MotorShield.h: No such file or directory
compilation terminated.
Error compiling.

**Comment by DavidEGrayson** [comment]
I took your long error message out of the subject line and give this thread a more appropriate subject line.  For reference, the original subject line was:

```
Arduino: 1.6.4 (Windows 7), Board: "Arduino Uno"  C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++ -c -g -Os -Wall -Wextra -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10604 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino -IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard C:\Users\RJEA26~1.STA\AppData\Local\Temp\build2119754585980147342.tmp\sketch_.cpp -o C:\Users\RJEA26~1.STA\AppData\Local\Temp\build2119754585980147342.tmp\sketch_.cpp.o  
sketch_.ino:1:36: fatal error: DualVNH5019MotorShield.h: No such file or directory compilation terminated.
Error compiling.
```

The main thing you should be looking at here is "DualVNH5019MotorShield.h: No such file or directory".  This means that the Arduino IDE is not finding the library.  You most likely installed the library incorrectly, and you should retry the instructions [here](https://github.com/pololu/dual-vnh5019-motor-shield).  Be sure to restart the Arduino IDE.

We use github issues to track issues or enhancements to the code.  If you continue to have trouble using the library, please post on our [forum](http://forum.pololu.com) instead of here.

**Comment by NGwpower** [comment]
Thank You for redirecting my post. What is it on the Polulu form?
RJ

               In GOD WE TRUST
           *****Proud Member of *****
      Veterans of Foreign Wars 1968-1971
Life Member 1998 Harley Owners Group
                         NMRA 2012 -

**Comment by DavidEGrayson** [comment]
You would need to log in to the forum and write a new post.

**Comment by NGwpower** [comment]
The Arduino forum gave me a zip file that worked, so have a good week.
