### ISSUE TITLE
About current measuring in the demo

### ISSUE THREAD

**Issue by robocop6** [pololu/dual-vnh5019-motor-shield#14]
Hello,

I've purchased a VNH5019 motor driver shield and 2 pololu motors (37Dx68L). When trying to read currents at a higher frequency (e.g. replacing the lines `(i%200 == 100)` for `(i%2 == 1)`), I get this (where horizontal axis is the index of each measure, and vertical axis is current in mA).

![image](https://cloud.githubusercontent.com/assets/11356544/17895165/92a332a6-6922-11e6-8d2d-210dea7ce29b.png)

Since the desired speed is an increasing and then decreasing ramp, I would have expected smoother results. I guess I could just use a low-pass filter to reduce noise, but I would like to know if this is a problem in the library that could be solved easily. Thanks in advance!

**Comment by DavidEGrayson** [comment]
Hello.  What board are you running the demo code on?

**Comment by robocop6** [comment]
Oh sry, I thought I had already told. It's an Arduino Mega.

**Comment by DavidEGrayson** [comment]
On the Arduino Mega 2560, this library uses analogWrite, which results in a 490 Hz PWM frequency.  The RC filters on each of the shield's current sense lines were designed for higher frequencies, so the behavior you are seeing is expected.  We are updating our documentation to reflect this.

**Comment by DavidEGrayson** [comment]
On the Arduino Mega 2560, this library uses analogWrite, which results in a 490&nbsp;Hz PWM frequency.  The RC filters on each of the shield's current sense lines were designed for higher frequencies, so the behavior you are seeing is expected.

If you add a 1&nbsp;&micro;F capacitor between the current sense output pin you are using (i.e. M1CS or M2CS) and GND, that should smooth out the signal.  Alternatively, it should be possible to modify the library so that it uses a higher PWM frequency such as 8&nbsp;kHz.

We are updating our documentation to reflect this.  You can see the "Current sense outputs" section that we added to the product page today for more information:

https://www.pololu.com/product/2507
